### ISSUE TITLE
An unset logo comes down in the project payload as an empty string

### ISSUE THREAD

**Issue by EddyLane** [velocity-ci/velocity#62]
I'm currently working around this by checking the length of the string, but I think a null value here would work better.

Thoughts?

**Comment by VJftw** [comment]
I should use pointers ^^

**Comment by VJftw** [comment]
@EddyLane  Out of interest, what would you do with a `null` logo? Might it be better for the backend to always provide a logo (even like a default logo e.g. https://github.com/MonarchsofCoding) or generate a logo with the first letter of the repo name e.g. https://github.com/discourse/letter-avatars

**Comment by EddyLane** [comment]
Yep, I think the ideal scenario is to display a letter/colour for that particular project, potentially from the service you've linked :)

I do however think this is a concern for the frontend rather then the backend so I still think the null is correct response unless you can convince me otherwise?
